# .pre-commit-config.yaml

repos:
  # Python hooks
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3
        files: ^backend/

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8]
        files: ^backend/

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        language_version: python3
        files: ^backend/

  # JavaScript hooks
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.11.1
    hooks:
      - id: eslint
        name: eslint
        entry: npx eslint
        language: node
        types: [javascript, jsx]
        files: ^frontend/

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier --write
        language: node
        types: [javascript, jsx, css, html, json, markdown]
        files: ^frontend/

  # YAML validation
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        files: \.(yml|yaml)$