version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smart-documents-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      - db
    volumes:
      - ./backend/app:/app/app
      - ./backend/tests:/app/tests
      - ./backend/requirements.txt:/app/requirements.txt

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smart-documents-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:5000"
      - "${LIVE_UPDATE_PORT}:35729"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development

  db:
    image: postgres:15
    container_name: smart-documents-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: smart_documents
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  db_data:
