"""Add price to items table

Revision ID: 426a9c6644ef
Revises:
Create Date: 2024-09-28 11:35:59.423071

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "426a9c6644ef"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_items_description", table_name="items")
    op.drop_index("ix_items_id", table_name="items")
    op.drop_index("ix_items_name", table_name="items")
    op.drop_table("items")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="items_pkey"),
    )
    op.create_index("ix_items_name", "items", ["name"], unique=False)
    op.create_index("ix_items_id", "items", ["id"], unique=False)
    op.create_index("ix_items_description", "items", ["description"], unique=False)
    # ### end Alembic commands ###
